
outputDir: test_data/test_out
preprocess: false
# Resources

refGenome: resources/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta

#SureSelect Human All Exon V7
bait: resources/S31285117_MergedProbes.bed
capture: resources/S31285117_Regions.bed


# Sample Information


samples:
    p1_normal:
        patientID: p1
        bam: test_data/gatk_test/p1_normal.final.bam
        tissue: normal
    p1_tumor:
        patientID: p1
        bam: test_data/gatk_test/p1_tumor.final.bam
        tissue: tumor

#    ZH0945:
#        patient_id: 15.861
#        tissue: normal
#
#    ZH0946:
#        patient_id: 15.861
#        tissue: tumor
#
#    ZH0947:
#        pateint_id: 23.006
#        tissue: normal
#
#    ZH0948:
#        patient_id:23.006
#        tissue: tumor
#
#    ZH0951:
#        patient_id: 29.178
#        tissue: normal
#
#    ZH0952:
#        patient_id: 29.178
#        tissue: tumor

# Trimming

skewer:
  Q: 30
  l: 50
  q: 35
  x: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
  y: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

# Mark Duplicates
MarkDuplicates:
    ram: 4

# Recalibration

recal_bam: true
# What VCF should this be?
#recalVCF: resources/small_exac_common_3.hg38.vcf.gz
# Mutect2

# Resource Files


gnomad: resources/af-only-gnomad.hg38.vcf.gz
known_indels: resources/resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf
pon: resources/somatic-hg38_1000g_pon.hg38.vcf.gz
known_variants: resources/small_exac_common_3.hg38.vcf.gz


# Parameters
parameters:
  -af-of-alleles-not-in-resource: 0.0000025
  -disable-read-filter: MateOnSameContigOrNoMappedMateReadFilter

scatter: 10

# Annotation

funcotatorSources: funcotator_dataSources.v1.6.20190124s
genomeVersion: hg38